#!/bin/bash

set -eu

source `dirname $0`/functions.sh

FTP="ftp://ftp.ncbi.nih.gov"

## Taxonomy
if check_or_mkdir "taxonomy"; then
    cd taxonomy
    wget $FTP/pub/taxonomy/taxdump.tar.gz
    tar -zxvf taxdump.tar.gz nodes.dmp
    tar -zxvf taxdump.tar.gz names.dmp
    rm tardump.tar.gz
    #wget $FTP/pub/taxonomy/gi_taxid_nucl.dmp.gz
    #gunzip gi_taxid_nucl.dmp.gz
    cd ..
fi


